<a href="https://colab.research.google.com/github/Oluwatobi09/python-class/blob/master/hash_analytic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt
from pandas import Series , DataFrame

##**NUMPY**

In [ ]:
# convention for importing numpy
import numpy as np
#creating arrays from a list
arr = [6, 7, 8, 9]
print(type(arr)) # prints <class 'list'>

a = np.array(arr)
print(type(a))  # prints <class 'numpy.ndarray'>
print(a.shape)  # prints (4,) - a is a 1d array with 4 items
print(a.dtype)  # prints int64

In [ ]:
#creating arrays from two lists
my_list1 = [1,2,3,4]
my_list2 = [5,6,7,8]
my_array = np.array([my_list1,my_list2])
print(my_array) #prints the 2d array
print(my_array.dtype)  #prints int64
print(my_array.shape) #prints the array shape (2, 4) 

In [ ]:
print(np.ones((2, 3))) # prints a 2x3 array of ones
print(np.zeros((2, 3))) # prints a 2x3 array of zeroes
print(np.zeros(5) ) # prints a 1x5 array of zeroes
print(np.identity(3)) # prints a 3x3 identity matrix 
print(np.eye(3)) #prints an identity matrix to the degree indicated
print(np.arange(5,50,4)) #prints a set of numbers between 5 and 50 skipping 4 everytime

In [6]:
my_array2 = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
my_array3 = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

my_array4 = np.array([[10, 11, 12],[13, 14, 15], 
              [16, 17, 18],[19, 20, 21]])

scalar Operations on Array


In [ ]:
print(my_array2 * my_array2) #prints the product of my_array and my_array2
print(my_array3 + my_array2) #prints the sum of my_array3 and my_array2
print(my_array2 - my_array3) #prints the difference between my_array2 and my_array3              
print(my_array4 ** 3) #prints the the value of my_array 4 exponential 3
print(1 / my_array ) #prints the recripocal of my_array

Array indexing


1.   1 dimensional array
2.   2 dimensional array



In [ ]:
''' 1 dimensional array'''
my_array5 = np.arange(2,20,2)
print(my_array5[5]) #prints the object with index 5 in the list

# the items within a list can can be edited by assigning values
my_array5[2:6] = 12
print (my_array5) #prints my_array5 with the 12 from index 2 to 5
my_array5[:] = 15 
print (my_array5) #prints all the values in the array as 15

#creating a copy of an array
my_array5copy = my_array5.copy()

''' 2 dimensional array'''
#the first object in the set represents the row and the second the column
print(my_array4[0]) #prints the first row in the row with index zero

#the elements in the rows can be accessed also 
print(my_array4[1][2]) #prints the element in the row index 1 and column index 2

#Elements in arrays  can also be retrieved by slicing rows and columns or a combination of indexing and slicing.
print(my_array3[1,  0:2]) #prints the elements in row index 1 and column index 0 to 2

# slicing
print(my_array4[:3, 1:] ) #prints the elements from row index up to 3 and column index from 1 to end

# the items within a list can can be edited by assigning values
my_array4[:2, 1:]  = 12
print (my_array4) #prints my_array4 with the 12 from row index up to 2 and column index from 1 to end



In [9]:
#using loops to index
arr_len = my_array4.shape[1] #shape returns (rows,columns)
print(arr_len) #prints the number of columns in my_array4
for i in range(arr_len):
  my_array4[i] = i
print (my_array4) #prints the sequence of values until the loop is satisfied

3
[[ 0  0  0]
 [ 1  1  1]
 [ 2  2  2]
 [19 20 21]]


In [ ]:
#other ways of accessing rows, the double square brackets indicate only rows
print(my_array4[[0,1]]) #prints all element on row index 0 and 1, zero first of the array
print(my_array4[[1,0]]) #prints all element on row index 0 and 1, one first  of the array

In [ ]:
#universal array functions
a = np.arange(1,15,2)
b = np.arange(2,16,2)
print(a) # prints an array of numbers within  the range 
print(b) # prints an array of numbers within  the range 
print(np.sqrt(a)) #sqrt prints the squareroot of a
print(np.exp(a)) #exp prints the exponential of a 
print(np.add(a,b)) #add adds the values of a and b
print(np.maximum(a,b)) #maximum prints the maximum between a and b
#additional resources on scipy.org

In [ ]:
#loading and saving arrays

In [ ]:
#statistical and mathematical processing of arrays
import matplotlib.pyplot as plt
axes_values = np.arange(2,50,5)
dx, dy = np.meshgrid(axes_values,axes_values)
print(dx)
function = 2*dx+3*dy
function2 =  np.cos(dx)+np.cos(dy)
print(function) #prints the result of the equation
plt.imshow(function) #displays the imshow for function
plt.title('function of 2dx+3dy')
print(plt.colorbar())
plt.imshow(function2) #displays the imshow for function2
plt.title('function of cos(dx)+cos(dy)')
print(plt.colorbar())

In [ ]:
#conditional clauses and boolean operations
x = np.array([100,200,300,400])
y = np.array([10,15,20,25])
condition = ([True,True,False,False])

z = np.where(condition, x, y)
print(z) #prints the element of X where true and of y where false

z1 = np.where(x>0,0,1) #returns zero if x>0 else returns 1
print(z1)

In [ ]:
#standard functions of numpy
print(x.sum()) #prints the sum of the values in the row
print(my_array4.sum(0)) #prints the sum of the values in the columns
print(my_array4.sum(1)) #prints the sum of values in the row
print(my_array4)
print(x.mean()) #prints the mean of values in the array
print(x.std()) #prints the standard deviation of values in the array
print(x.var()) #prints the variance of values in the array

In [ ]:
#logical operations (and /or  operations)
condition2 = np.array([True,False,True])
print(condition2.any()) #returns true if any is true, or operator
print(condition2.all()) #returns true if all are true, else it returns false, and operator

In [ ]:
#sorting in numpy arrays
unsorted_array = np.array([5,8,5,8,98,21,15,85,25,94])
unsorted_array.sort()
print(unsorted_array) #prints the sorted elements of the list
print(np.unique(unsorted_array)) #prints the unique elements in a list
print(np.in1d([5,8,9,60,87],unsorted_array)) #prints the boolean value of the value in the 1 dimensional array

##**PANDAS**

In [ ]:
#working with Series in pandas
object = Series([1,5,5,44,4,4,4])
print(object) #prints the values in series and their index
print(object.values) #prints the values in the series only
print(object.index) #prints the index in the series only

#using numpy array to form series
my_array7 = np.arange(2,20,2)
b = Series(my_array7)
print(b) #prints my_array7 as a Series

#the index of series can be customized to what is desired
c = Series(my_array7,index=[10,20,30,40,50,60,70,80,90])
print(c) #prints my_array7 as a Series with the customized index
d = Series(my_array7,index=['one','two','three','four','five','six','seven','eight','nine'])
print(d) #prints my_array7 as a Series with the customized index of strings

#indexing series
print(d['six']) #prints the element of 'd' with index of six

#using conditions in series
print(d[d>8]) #prints only elements greater than 8

#using booleans in series
print(56 in d) #prints True/False of the value in the series

#converting series to dictionaries
d_dictionary = d.to_dict()
print(d_dictionary) #prints out the series as a dictionary

# #dealing with missing values(nan)
index_2=['one','two','three','four','five','six','seven','eight','nine','ten','eleven']
d1 = Series(d,index_2)
print(pd.isnull(d1)) #prints True for Nan and False for where the value exists
print(pd.notnull(d1)) #prints the opposite of 'isnull'

#addition of series
print(d+d1) #prints the sum of the values with the corresponding index

#
d1.name = "degrees"
d1.index.name = "numbers"
print(d1)

#replacing values in series
s1 = Series([10,20,40,50,20,10,50,10])
print(s1)
print(s1.replace(50,np.nan)) #replaces 50 with nan
print(s1.replace([10,20,50],[100,200,500])) #replacing using lists
print(s1.replace({10:100,20:np.nan,40:400})) #replacing using dictionary

In [ ]:
#working with dataframe
revenue = pd.read_html('https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue')
print(revenue)
#using Dictionary to Dataframe
df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
           'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'],
           'Population': [10000, 8500, 35000, 12000],
           'Age': [60, 70, 80, 75]
}
df = pd.DataFrame(df_dict, index=[2, 4, 6, 8])
print(df)
print(df.columns) #prints the columns in the dataset
print(df['Capital']) #prints the values of only the Capital column
print(DataFrame(df,columns=['Capital','Population'])) #prints only Capital and population columns
print(df.head(2)) #prints the first two rows of the table
print(df.tail(2)) #prints the last two rows of the table
print(df.iloc[0]) #prints all the details on row 1

#assigning values to df using numpy
new_array = np.array([50,75,100,25])
df['GDP'] = new_array
print(df) #prints a new column with the array values named GDP

#assigning values to df using Series
Growth_index = Series([5,7,2,3],index=[1,2,3,4])
df['Growth_index'] = Growth_index
print(df) #prints a new column with the Series values named Growth_index

#deleting a column using from the df
del df['Growth_index']
print(df) #prints the dataframe after removing Growth_index


In [ ]:
#indexing objects in dataframe and series
print(df.index) #prints the index of the dataframe
#negative index
print(df.index[-2:]) #eliminates the first two elements of the series
print(df.index[:-2]) #eliminates the last two elements of the series
print(df.index[2:4]) #prints index 2 to less than 4

In [ ]:
#reindexing methods
c1 = Series([1,2,3,4,5,6,7,8,9,10],index=[0,10,20,30,40,50,60,70,80,90])
print(c1)
c2 = c1.reindex([0,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90])
print(c2) #creates new index using reindex
c3 = c1.reindex([0,10,15,20,25,30,35,40,45,50,55,60,
                 65,70,75,80,85,90,95,100], fill_value= 10)
print(c3) #creates new index using reindex fill the values as 10

#'forward fill' fills all values in the range of the index with the value of the last index
c4 = c1.reindex(range(100), method='ffill')
print(c4) 




In [ ]:
#creating dataframe using randn
from numpy.random import randn
df_random = DataFrame(randn(25).reshape(5,5),
                      index=[1,2,3,4,5], columns=['a','b','c','d','e'])
print(df_random)
#reindexing rows and columns
df_random1 = df_random.reindex([1,2,3,4,5,6],
                               columns= ['a','b','c','d','e','f'],fill_value=1)
print(df_random1) #prints the dataframe with new rows and columns and filled with 1
#dropping values from rows and columns
df_random2 = df_random1.drop(6)
print(df_random2) #deletes the row with index 6
#for columns the axis '1' must be specified
df_random3 = df_random2.drop('f',axis=1) #deletes the column 'f'
print(df_random3) #deletes the column with label 'f'


In [ ]:
#handling missing data
df_dict2 = {'Name': ['James', 'Yemen', 'Caro', np.nan],
           'Profession': ['Researcher', 'Artist', 'Doctor', 'Writer'],
           'Experience': [12, np.nan, 10, 8],
            'Sex': [np.nan,np.nan,np.nan,np.nan],
           'Height': [np.nan, 175, 180, 150]}
new_df = pd.DataFrame(df_dict2)
print(new_df)
print(new_df.isnull()) #retuns true or false for nan values
print(new_df.dropna()) #drops all rows with nan values
print(new_df.dropna(how='all',axis=1)) #drops only columns with all values nan 
print(new_df.dropna(thresh=3,axis=1)) #drops any columns without at least 3 values
print(new_df.fillna({'Name': 'Tunde',
           'Profession': 'lawyer',
           'Experience': 1,
            'Sex': 'Male',
           'Height': 170})) #fills the nan with a dictionary


In [ ]:
df_dict4 = {'Country': ['Senegal', 'Kenya', 'Ethiopia', 'Togo'],
           'Capital': ['Bamako', 'Nairobi', 'Addis Ababa', 'Lome'],
           'Population': [8000, 8500, 35000, 12000],
           'Age': [60, 70, 65,80]
}
df4 = pd.DataFrame(df_dict4, index=[2, 4, 6, 8])
df4

In [24]:
df_dict5 = {'Country': ['Senegal', np.nan, 'Ethiopia', 'Togo'],
           'Capital': ['Bamako', 'Nairobi', 'Addis Ababa', np.nan],
           'Population': [np.nan, 8500, np.nan, 12000],
           'Age': [60, np.nan, 65,80]
}
df5 = pd.DataFrame(df_dict5, index=[2, 4, 6, 8])
print(df5)

# combining dataframes
df6 = df5.combine_first(df4)
print(df6) #prints the values of df5 with the nan values replaced from df4

    Country      Capital  Population   Age
2   Senegal       Bamako         NaN  60.0
4       NaN      Nairobi      8500.0   NaN
6  Ethiopia  Addis Ababa         NaN  65.0
8      Togo          NaN     12000.0  80.0
    Country      Capital  Population   Age
2   Senegal       Bamako      8000.0  60.0
4     Kenya      Nairobi      8500.0  70.0
6  Ethiopia  Addis Ababa     35000.0  65.0
8      Togo         Lome     12000.0  80.0


In [ ]:
#merging dataframes
merger = pd.merge(df,df4)
merger #prints only columns that are the same in both dataframes

In [ ]:
#merging dataframes based on a column
merger2 = pd.merge(df,df4,on='Country') # how='inner' gives the same result
merger2 #prints only columns with same 'country' the same in both dataframes

In [ ]:
merger3 = pd.merge(df,df4,on='Country',how='left')
merger3 #prints the columns of the dataframe on the left and merges with the right

In [ ]:
merger4 = pd.merge(df,df4,on='Country',how='outer',suffixes=('_first','_second'))
merger4 #prints the columns of the dataframe listing all 'country' values

In [ ]:
merger5 = pd.merge(df,df4,on='Country',how='outer',right_index=True)
merger5 #references the index of the df on the right

In [ ]:
#concatenation entails combining all elements in the dataframes
concat_1 = pd.concat([df,df4])
print(concat_1) #prints the first dataframe then the second based on rows
concat_2 = pd.concat([df,df4],axis=1)
print(concat_2) #prints the first dataframe then the second based on columns
concat_3 = pd.concat([df,df4],ignore_index=True)
print(concat_3) #prints the new dataframe with new index

In [ ]:
#join two dataframes, suffixes are important
df.join(df4,lsuffix="_first",rsuffix='_second') 

In [ ]:
#pandas statistics
df['Population'].sum() #prints the sum of values in the population column
print(df.mean()) #prints the mean of all the column with numbers
print(df.max()) #prints the maximum number in every row with numbers
print(df.min()) #prints the minimum values in every row with numbers 
print(df.cumsum()) #prints the cummulative sum at every row


In [30]:
df.describe()  #details the max, min, count, mean, standard deviation of a dataframe

Population        Age         GDP
count      4.000000   4.000000    4.000000
mean   16375.000000  71.250000   62.500000
std    12499.166639   8.539126   32.274861
min     8500.000000  60.000000   25.000000
25%     9625.000000  67.500000   43.750000
50%    11000.000000  72.500000   62.500000
75%    17750.000000  76.250000   81.250000
max    35000.000000  80.000000  100.000000

In [ ]:
#reshaping dataframes to stack and unstack
df7 = DataFrame(np.arange(8).reshape(2,4),
                index=pd.Index(['uber','grab'],name='cabs'),
                columns=pd.Index(['c1','c2','c3','c4'],name='attributes'))
print(df7)
df7.stack(dropna=False) #prints the stacked dataframe

In [ ]:
#pivot table
df_list = pd.read_html('https://en.wikipedia.org/wiki/Pivot_table')
df8 = df_list[0]
df8
df8.pivot('Date of sale','Sales person','Total price')

In [32]:
#handling duplicates
df9 = DataFrame({
    'col1':['uber','uber','uber','uber','ola'],
    'col2': [5,4,3,3,5]
})
print(df9)
# print(df9.duplicated()) #prints the boolean of rows for duplicates
# print(df9.drop_duplicates()) #deletes the duplicated rows
# print(df9.drop_duplicates(['col1'])) #drops duplicates in the 'col1'
# print(df9.drop_duplicates(['col2'],keep='last')) #deletes the duplicates leaving the last

   col1  col2
0  uber     5
1  uber     4
2  uber     3
3  uber     3
4   ola     5


In [33]:
#mapping
GDP = {'uber':20, 'uber':58, 'uber': 56, 'uber':25, 'ola':34}
df9['GDP'] = df9['col1'].map(GDP)
df9

col1  col2  GDP
0  uber     5   25
1  uber     4   25
2  uber     3   25
3  uber     3   25
4   ola     5   34